/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "brain_controller.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(resetRequest, resetRequest, AUTO)


PB_BIND(getStateSetTargetRequest, getStateSetTargetRequest, AUTO)


PB_BIND(resetResponse, resetResponse, AUTO)


PB_BIND(getStateSetTargetResponse, getStateSetTargetResponse, AUTO)




