# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: brain_controller.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x62rain_controller.proto\"\xcc\x01\n\x0cresetRequest\x12\x12\n\nMAX_CART_X\x18\x01 \x01(\x02\x12\x12\n\nMAX_CART_V\x18\x02 \x01(\x02\x12\x13\n\x0bMATX_CART_A\x18\x03 \x01(\x02\x12\x10\n\x08HW_MAX_X\x18\x04 \x01(\x02\x12\x10\n\x08HW_MAX_V\x18\x05 \x01(\x02\x12\x10\n\x08HW_MAX_A\x18\x06 \x01(\x02\x12\x17\n\x0fMAX_THRESHOLD_X\x18\x07 \x01(\x02\x12\x17\n\x0fMAX_THRESHOLD_V\x18\x08 \x01(\x02\x12\x17\n\x0fMAX_THRESHOLD_A\x18\t \x01(\x02\"P\n\x18getStateSetTargetRequest\x12\x10\n\x08TARGET_X\x18\x01 \x01(\x02\x12\x10\n\x08TARGET_V\x18\x02 \x01(\x02\x12\x10\n\x08TARGET_A\x18\x03 \x01(\x02\"\xcc\x01\n\rresetResponse\x12\x12\n\nMAX_CART_X\x18\x01 \x01(\x02\x12\x12\n\nMAX_CART_V\x18\x02 \x01(\x02\x12\x12\n\nMAX_CART_A\x18\x03 \x01(\x02\x12\x10\n\x08HW_MAX_X\x18\x04 \x01(\x02\x12\x10\n\x08HW_MAX_V\x18\x05 \x01(\x02\x12\x10\n\x08HW_MAX_A\x18\x06 \x01(\x02\x12\x17\n\x0fMAX_THRESHOLD_X\x18\x07 \x01(\x02\x12\x17\n\x0fMAX_THRESHOLD_V\x18\x08 \x01(\x02\x12\x17\n\x0fMAX_THRESHOLD_A\x18\t \x01(\x02\"\xc8\x01\n\x19getStateSetTargetResponse\x12\x13\n\x0b\x43URR_CART_X\x18\x01 \x01(\x02\x12\x13\n\x0b\x43URR_CART_V\x18\x02 \x01(\x02\x12\x13\n\x0b\x43URR_CART_A\x18\x03 \x01(\x02\x12\x17\n\x0f\x43URR_POLE_ANGLE\x18\x04 \x01(\x02\x12\x13\n\x0b\x43URR_POLE_V\x18\x05 \x01(\x02\x12\x12\n\nCURR_IMU_A\x18\x06 \x01(\x02\x12\x14\n\x0c\x43URR_MOTOR_X\x18\x07 \x01(\x02\x12\x14\n\x0c\x43URR_MOTOR_V\x18\x08 \x01(\x02*\"\n\rcurrentStatus\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x62\x06proto3')

_CURRENTSTATUS = DESCRIPTOR.enum_types_by_name['currentStatus']
currentStatus = enum_type_wrapper.EnumTypeWrapper(_CURRENTSTATUS)
OK = 0
ERROR = 1


_RESETREQUEST = DESCRIPTOR.message_types_by_name['resetRequest']
_GETSTATESETTARGETREQUEST = DESCRIPTOR.message_types_by_name['getStateSetTargetRequest']
_RESETRESPONSE = DESCRIPTOR.message_types_by_name['resetResponse']
_GETSTATESETTARGETRESPONSE = DESCRIPTOR.message_types_by_name['getStateSetTargetResponse']
resetRequest = _reflection.GeneratedProtocolMessageType('resetRequest', (_message.Message,), {
  'DESCRIPTOR' : _RESETREQUEST,
  '__module__' : 'brain_controller_pb2'
  # @@protoc_insertion_point(class_scope:resetRequest)
  })
_sym_db.RegisterMessage(resetRequest)

getStateSetTargetRequest = _reflection.GeneratedProtocolMessageType('getStateSetTargetRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSTATESETTARGETREQUEST,
  '__module__' : 'brain_controller_pb2'
  # @@protoc_insertion_point(class_scope:getStateSetTargetRequest)
  })
_sym_db.RegisterMessage(getStateSetTargetRequest)

resetResponse = _reflection.GeneratedProtocolMessageType('resetResponse', (_message.Message,), {
  'DESCRIPTOR' : _RESETRESPONSE,
  '__module__' : 'brain_controller_pb2'
  # @@protoc_insertion_point(class_scope:resetResponse)
  })
_sym_db.RegisterMessage(resetResponse)

getStateSetTargetResponse = _reflection.GeneratedProtocolMessageType('getStateSetTargetResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETSTATESETTARGETRESPONSE,
  '__module__' : 'brain_controller_pb2'
  # @@protoc_insertion_point(class_scope:getStateSetTargetResponse)
  })
_sym_db.RegisterMessage(getStateSetTargetResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CURRENTSTATUS._serialized_start=725
  _CURRENTSTATUS._serialized_end=759
  _RESETREQUEST._serialized_start=27
  _RESETREQUEST._serialized_end=231
  _GETSTATESETTARGETREQUEST._serialized_start=233
  _GETSTATESETTARGETREQUEST._serialized_end=313
  _RESETRESPONSE._serialized_start=316
  _RESETRESPONSE._serialized_end=520
  _GETSTATESETTARGETRESPONSE._serialized_start=523
  _GETSTATESETTARGETRESPONSE._serialized_end=723
# @@protoc_insertion_point(module_scope)
