# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: brain_controller.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x62rain_controller.proto\"\xb9\x01\n\x0cResetRequest\x12\x10\n\x08maxCartX\x18\x01 \x01(\x02\x12\x10\n\x08maxCartV\x18\x02 \x01(\x02\x12\x10\n\x08maxCartA\x18\x03 \x01(\x02\x12\x0e\n\x06hwMaxX\x18\x04 \x01(\x02\x12\x0e\n\x06hwMaxV\x18\x05 \x01(\x02\x12\x0e\n\x06hwMaxA\x18\x06 \x01(\x02\x12\x15\n\rmaxThresholdX\x18\x07 \x01(\x02\x12\x15\n\rmaxThresholdV\x18\x08 \x01(\x02\x12\x15\n\rmaxThresholdA\x18\t \x01(\x02\"P\n\x18GetStateSetTargetRequest\x12\x10\n\x08TARGET_X\x18\x01 \x01(\x02\x12\x10\n\x08TARGET_V\x18\x02 \x01(\x02\x12\x10\n\x08TARGET_A\x18\x03 \x01(\x02\"\xba\x01\n\rResetResponse\x12\x10\n\x08maxCartX\x18\x01 \x01(\x02\x12\x10\n\x08maxCartV\x18\x02 \x01(\x02\x12\x10\n\x08maxCartA\x18\x03 \x01(\x02\x12\x0e\n\x06hwMaxX\x18\x04 \x01(\x02\x12\x0e\n\x06hwMaxV\x18\x05 \x01(\x02\x12\x0e\n\x06hwMaxA\x18\x06 \x01(\x02\x12\x15\n\rmaxThresholdX\x18\x07 \x01(\x02\x12\x15\n\rmaxThresholdV\x18\x08 \x01(\x02\x12\x15\n\rmaxThresholdA\x18\t \x01(\x02\"\xb8\x01\n\x19GetStateSetTargetResponse\x12\x11\n\tcurrCartX\x18\x01 \x01(\x02\x12\x11\n\tcurrCartV\x18\x02 \x01(\x02\x12\x11\n\tcurrCartA\x18\x03 \x01(\x02\x12\x15\n\rcurrPoleAngle\x18\x04 \x01(\x02\x12\x11\n\tcurrPoleV\x18\x05 \x01(\x02\x12\x10\n\x08\x63urrImuA\x18\x06 \x01(\x02\x12\x12\n\ncurrMotorX\x18\x07 \x01(\x02\x12\x12\n\ncurrMotorV\x18\x08 \x01(\x02*\"\n\rcurrentStatus\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x62\x06proto3')

_CURRENTSTATUS = DESCRIPTOR.enum_types_by_name['currentStatus']
currentStatus = enum_type_wrapper.EnumTypeWrapper(_CURRENTSTATUS)
OK = 0
ERROR = 1


_RESETREQUEST = DESCRIPTOR.message_types_by_name['ResetRequest']
_GETSTATESETTARGETREQUEST = DESCRIPTOR.message_types_by_name['GetStateSetTargetRequest']
_RESETRESPONSE = DESCRIPTOR.message_types_by_name['ResetResponse']
_GETSTATESETTARGETRESPONSE = DESCRIPTOR.message_types_by_name['GetStateSetTargetResponse']
ResetRequest = _reflection.GeneratedProtocolMessageType('ResetRequest', (_message.Message,), {
  'DESCRIPTOR' : _RESETREQUEST,
  '__module__' : 'brain_controller_pb2'
  # @@protoc_insertion_point(class_scope:ResetRequest)
  })
_sym_db.RegisterMessage(ResetRequest)

GetStateSetTargetRequest = _reflection.GeneratedProtocolMessageType('GetStateSetTargetRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSTATESETTARGETREQUEST,
  '__module__' : 'brain_controller_pb2'
  # @@protoc_insertion_point(class_scope:GetStateSetTargetRequest)
  })
_sym_db.RegisterMessage(GetStateSetTargetRequest)

ResetResponse = _reflection.GeneratedProtocolMessageType('ResetResponse', (_message.Message,), {
  'DESCRIPTOR' : _RESETRESPONSE,
  '__module__' : 'brain_controller_pb2'
  # @@protoc_insertion_point(class_scope:ResetResponse)
  })
_sym_db.RegisterMessage(ResetResponse)

GetStateSetTargetResponse = _reflection.GeneratedProtocolMessageType('GetStateSetTargetResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETSTATESETTARGETRESPONSE,
  '__module__' : 'brain_controller_pb2'
  # @@protoc_insertion_point(class_scope:GetStateSetTargetResponse)
  })
_sym_db.RegisterMessage(GetStateSetTargetResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CURRENTSTATUS._serialized_start=672
  _CURRENTSTATUS._serialized_end=706
  _RESETREQUEST._serialized_start=27
  _RESETREQUEST._serialized_end=212
  _GETSTATESETTARGETREQUEST._serialized_start=214
  _GETSTATESETTARGETREQUEST._serialized_end=294
  _RESETRESPONSE._serialized_start=297
  _RESETRESPONSE._serialized_end=483
  _GETSTATESETTARGETRESPONSE._serialized_start=486
  _GETSTATESETTARGETRESPONSE._serialized_end=670
# @@protoc_insertion_point(module_scope)
