/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "brain_controller.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ResetRequest, ResetRequest, AUTO)


PB_BIND(GetStateSetTargetRequest, GetStateSetTargetRequest, AUTO)


PB_BIND(ResetResponse, ResetResponse, AUTO)


PB_BIND(GetStateSetTargetResponse, GetStateSetTargetResponse, AUTO)




