/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_BRAIN_CONTROLLER_PB_H_INCLUDED
#define PB_BRAIN_CONTROLLER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _currentStatus { 
    currentStatus_OK = 0, 
    currentStatus_ERROR = 1 
} currentStatus;

/* Struct definitions */
typedef struct _GetStateSetTargetRequest { 
    float TARGET_X; 
    float TARGET_V; 
    float TARGET_A; 
} GetStateSetTargetRequest;

typedef struct _GetStateSetTargetResponse { 
    float currCartX; /* current cart position float */
    float currCartV; /* current cart velocity float */
    float currCartA; /* current cart acceleration */
    float currPoleAngle; /* current pole angle */
    float currPoleV; /* current pole angular velocity */
    float currImuA; /* current IMU measured cart acceleration */
    float currMotorX; /* current motor shaft position (radians) */
    float currMotorV; /* motor shaft velocity (rad/sec) */
} GetStateSetTargetResponse;

/* Only the brain sends requests */
typedef struct _ResetRequest { 
    float maxCartX; 
    float maxCartV; 
    float maxCartA; 
    float hwMaxX; 
    float hwMaxV; 
    float hwMaxA; 
    float maxThresholdX; 
    float maxThresholdV; 
    float maxThresholdA; 
} ResetRequest;

/* Only the controller responds */
typedef struct _ResetResponse { 
    float maxCartX; 
    float maxCartV; 
    float maxCartA; 
    float hwMaxX; 
    float hwMaxV; 
    float hwMaxA; 
    float maxThresholdX; 
    float maxThresholdV; 
    float maxThresholdA; /* TODO:debug led? */
} ResetResponse;


/* Helper constants for enums */
#define _currentStatus_MIN currentStatus_OK
#define _currentStatus_MAX currentStatus_ERROR
#define _currentStatus_ARRAYSIZE ((currentStatus)(currentStatus_ERROR+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ResetRequest_init_default                {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define GetStateSetTargetRequest_init_default    {0, 0, 0}
#define ResetResponse_init_default               {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define GetStateSetTargetResponse_init_default   {0, 0, 0, 0, 0, 0, 0, 0}
#define ResetRequest_init_zero                   {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define GetStateSetTargetRequest_init_zero       {0, 0, 0}
#define ResetResponse_init_zero                  {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define GetStateSetTargetResponse_init_zero      {0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define GetStateSetTargetRequest_TARGET_X_tag    1
#define GetStateSetTargetRequest_TARGET_V_tag    2
#define GetStateSetTargetRequest_TARGET_A_tag    3
#define GetStateSetTargetResponse_currCartX_tag  1
#define GetStateSetTargetResponse_currCartV_tag  2
#define GetStateSetTargetResponse_currCartA_tag  3
#define GetStateSetTargetResponse_currPoleAngle_tag 4
#define GetStateSetTargetResponse_currPoleV_tag  5
#define GetStateSetTargetResponse_currImuA_tag   6
#define GetStateSetTargetResponse_currMotorX_tag 7
#define GetStateSetTargetResponse_currMotorV_tag 8
#define ResetRequest_maxCartX_tag                1
#define ResetRequest_maxCartV_tag                2
#define ResetRequest_maxCartA_tag                3
#define ResetRequest_hwMaxX_tag                  4
#define ResetRequest_hwMaxV_tag                  5
#define ResetRequest_hwMaxA_tag                  6
#define ResetRequest_maxThresholdX_tag           7
#define ResetRequest_maxThresholdV_tag           8
#define ResetRequest_maxThresholdA_tag           9
#define ResetResponse_maxCartX_tag               1
#define ResetResponse_maxCartV_tag               2
#define ResetResponse_maxCartA_tag               3
#define ResetResponse_hwMaxX_tag                 4
#define ResetResponse_hwMaxV_tag                 5
#define ResetResponse_hwMaxA_tag                 6
#define ResetResponse_maxThresholdX_tag          7
#define ResetResponse_maxThresholdV_tag          8
#define ResetResponse_maxThresholdA_tag          9

/* Struct field encoding specification for nanopb */
#define ResetRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    maxCartX,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    maxCartV,          2) \
X(a, STATIC,   SINGULAR, FLOAT,    maxCartA,          3) \
X(a, STATIC,   SINGULAR, FLOAT,    hwMaxX,            4) \
X(a, STATIC,   SINGULAR, FLOAT,    hwMaxV,            5) \
X(a, STATIC,   SINGULAR, FLOAT,    hwMaxA,            6) \
X(a, STATIC,   SINGULAR, FLOAT,    maxThresholdX,     7) \
X(a, STATIC,   SINGULAR, FLOAT,    maxThresholdV,     8) \
X(a, STATIC,   SINGULAR, FLOAT,    maxThresholdA,     9)
#define ResetRequest_CALLBACK NULL
#define ResetRequest_DEFAULT NULL

#define GetStateSetTargetRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    TARGET_X,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    TARGET_V,          2) \
X(a, STATIC,   SINGULAR, FLOAT,    TARGET_A,          3)
#define GetStateSetTargetRequest_CALLBACK NULL
#define GetStateSetTargetRequest_DEFAULT NULL

#define ResetResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    maxCartX,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    maxCartV,          2) \
X(a, STATIC,   SINGULAR, FLOAT,    maxCartA,          3) \
X(a, STATIC,   SINGULAR, FLOAT,    hwMaxX,            4) \
X(a, STATIC,   SINGULAR, FLOAT,    hwMaxV,            5) \
X(a, STATIC,   SINGULAR, FLOAT,    hwMaxA,            6) \
X(a, STATIC,   SINGULAR, FLOAT,    maxThresholdX,     7) \
X(a, STATIC,   SINGULAR, FLOAT,    maxThresholdV,     8) \
X(a, STATIC,   SINGULAR, FLOAT,    maxThresholdA,     9)
#define ResetResponse_CALLBACK NULL
#define ResetResponse_DEFAULT NULL

#define GetStateSetTargetResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    currCartX,         1) \
X(a, STATIC,   SINGULAR, FLOAT,    currCartV,         2) \
X(a, STATIC,   SINGULAR, FLOAT,    currCartA,         3) \
X(a, STATIC,   SINGULAR, FLOAT,    currPoleAngle,     4) \
X(a, STATIC,   SINGULAR, FLOAT,    currPoleV,         5) \
X(a, STATIC,   SINGULAR, FLOAT,    currImuA,          6) \
X(a, STATIC,   SINGULAR, FLOAT,    currMotorX,        7) \
X(a, STATIC,   SINGULAR, FLOAT,    currMotorV,        8)
#define GetStateSetTargetResponse_CALLBACK NULL
#define GetStateSetTargetResponse_DEFAULT NULL

extern const pb_msgdesc_t ResetRequest_msg;
extern const pb_msgdesc_t GetStateSetTargetRequest_msg;
extern const pb_msgdesc_t ResetResponse_msg;
extern const pb_msgdesc_t GetStateSetTargetResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ResetRequest_fields &ResetRequest_msg
#define GetStateSetTargetRequest_fields &GetStateSetTargetRequest_msg
#define ResetResponse_fields &ResetResponse_msg
#define GetStateSetTargetResponse_fields &GetStateSetTargetResponse_msg

/* Maximum encoded size of messages (where known) */
#define GetStateSetTargetRequest_size            15
#define GetStateSetTargetResponse_size           40
#define ResetRequest_size                        45
#define ResetResponse_size                       45

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
